# ===================================================================
# Spring Boot configuration for the "secret-samples" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Samples for required secrets to be used in development and ci using prod profile.
# ===================================================================

spring:
  r2dbc:
    username: gateway
    password:

jhipster:
  security:
    authentication:
      jwt:
        base64-secret: OTgzNmQzNGEwNmU0NGY2NDIzNGMyMjRlMjc5MzRhMGQzMWU0Njg5YjY2OGM3OTFlNWM0MjA5ZWEzZGRlOWNlOGZjMzEyYzc1NmZiYWQxMzJjM2UwZDE1ZTk0NGZiYjJkN2E5YzgzOGM4MTlhYmQ3NTViNDVhMjE1MWNjYzYxNTY=
