configserver:
  name: Docker Consul Service
  status: Connected to Consul Server running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MzZlYjRiMjkwMTMyZTdhYzA1NTVhMzcyZmYyZGM4ZmFhNDMwMTY5MjI5NzllYWM3MzRjMTVkY2FhZDIwZDMzYzI0MmRjMTQ2Njc3MmIwYWFlZjI2MmIzYmNiYzlhY2FhYWQxOGUxMDE4MWQ4ZTYyNGNkZGIzMzI4ZTdiZTQ5OTQ=
